name: befluttermyfriend
description: A flutter game

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^0.10.2
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.2
  audioplayers: ^0.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Image Assets
    - assets/images/explosion/1.png
    - assets/images/explosion/2.png
    - assets/images/explosion/3.png
    - assets/images/explosion/4.png
    - assets/images/explosion/5.png
    - assets/images/explosion/6.png
    - assets/images/explosion/7.png
    - assets/images/explosion/8.png
    - assets/images/explosion/9.png

    - assets/images/air_mochi.png
    - assets/images/alien_mochi.png
    - assets/images/basic_mochi.png
    - assets/images/blaze_mochi.png
    - assets/images/heartless_mochi.png
    - assets/images/ice_mochi.png
    - assets/images/pleb.png
    - assets/images/background.jpg
    - assets/images/menu_background.png

    - assets/images/restart-button.png
    - assets/images/pause-button.png
    - assets/images/play-button.png

    - assets/images/music_on.png
    - assets/images/music_off.png
    - assets/images/sound_on.png
    - assets/images/sound_off.png

    - assets/images/trophy.png
    - assets/images/trophy-2.png
    - assets/images/trophy-3.png

    # Audio assets
    - assets/audio/menu_music.mp3
    - assets/audio/game_music.mp3
    - assets/audio/button_tap.mp3

  fonts:
    - family: Goodlight
      fonts:
        - asset: fonts/Goodlight.otf

    - family: Roundish Toons
      fonts:
        - asset: fonts/RoundishToons.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
